# BacktestConfig w/ allowed keys: {model}.
#
# Initial simple model. Hyperparameters are a first pass.
model:
  fit_predict_callable: fcstnyctaxi.models.xgboost_weekly.xgboost_weekly
  predict_callable: fcstnyctaxi.models.xgboost_weekly.xgboost_weekly_predict
  hyperparameters:
    freq: W-SUN
    lags: [1, 52]
    rolling_mean_window: 4
    max_depth: 6
    learning_rate: 0.05
    min_child_weight: 1
    n_estimators: 1000
    n_jobs: 1
