FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

RUN apt-get install build-essential ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app/

COPY pyproject.toml uv.lock README.md ./

RUN uv sync --locked --no-cache --no-dev --group extract --no-install-project --no-editable
