project_settings:
  project_id: "nyc-taxi-ehc"
  location: "us-central1"
  env: "dev"
  bucket_name: "nyc-taxi-ehc--modeling"

docker:
  extract_db_to_bucket: "us-central1-docker.pkg.dev/nyc-taxi-ehc/forecasting-pipeline/extract-db-to-bucket:f286db5"

vertex:
  pipeline_service_account: "fcst-data-ingress-pipeline-runner@nyc-taxi-ehc.iam.gserviceaccount.com"
  pipeline_root: "gs://nyc-taxi-ehc--modeling/vertex-pipeline-roots/"
  display_name_prefix: "fcst-data-ingress-pipeline"

extract_db_to_bucket:
  sql_filename: "initial_daily_taxi_rides.sql"
  sql_params: {}
  gcs_prefix: "dev/initial_datapull"
  output_filename: "manhattan_daily_zone_pickups.parquet"
