# GCP settings
project_settings:
  project_id: "nyc-taxi-ehc"
  location: "us-central1"
  env: "dev" # Only allowed: "dev", "test", "prod"

debug_allowlist:
  debug_enabled: False # Only allowed: True, False